USE [master]
GO

/****** Object:  Database [TimeSheets]    Script Date: 02/12/2023 21:14:57 ******/
CREATE DATABASE [TimeSheets]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimeSheets', FILENAME = N'/var/opt/mssql/data/TimeSheets.mdf' , SIZE = 40960KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TimeSheets_log', FILENAME = N'/var/opt/mssql/data/TimeSheets_log.ldf' , SIZE = 20480KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimeSheets].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TimeSheets] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TimeSheets] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TimeSheets] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TimeSheets] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TimeSheets] SET ARITHABORT OFF 
GO

ALTER DATABASE [TimeSheets] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TimeSheets] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TimeSheets] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TimeSheets] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TimeSheets] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TimeSheets] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TimeSheets] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TimeSheets] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TimeSheets] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TimeSheets] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TimeSheets] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TimeSheets] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TimeSheets] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TimeSheets] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TimeSheets] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TimeSheets] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TimeSheets] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TimeSheets] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TimeSheets] SET  MULTI_USER 
GO

ALTER DATABASE [TimeSheets] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TimeSheets] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TimeSheets] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TimeSheets] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TimeSheets] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TimeSheets] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TimeSheets] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TimeSheets] SET  READ_WRITE 
GO


